### ISSUE TITLE
Adding Dynamics On/Off

### ISSUE THREAD

**Issue by jtjart** [bitfocus/companion-module-yamaha-rcp#21]
Thank you for developing this project.

I have a request reagrding the Dynamics of a channel.
Is it possible to trigger the On/Off Button from the Dynamics of a channel?
Something like: InCh/Dyna1/OnOff

**Comment by MeestorX** [comment]
Hello;
The commands available are the ones that Yamaha has implemented with their SCP protocol. If you don’t find the command you want, it’s because Yamaha didn’t implement it.
To do what you want, you should use the Yamaha-MIDI module, available in my custom companion build. You can download it from my web site: discourse.remotely-possible.com
